version: "3.8"
services:
  vote:
    build: ./vote
    depends_on:
      - redis

  redis:
    image: redis:alpine

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    build: ./result
    depends_on:
      - db

volumes:
  db-data:

